FROM python:3.12-slim

WORKDIR /usr/app

# Install dbt-core and dbt-postgres adapter
RUN apt update && \
    apt install -y gcc && \
    apt install -y git && \
    pip install dbt-core dbt-postgres

# Copy your dbt project (if not mounted via volume)
# COPY ./my_sample_dbt /usr/app/my_sample_dbt

# Set the entrypoint to dbt
CMD ["bash"]