services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dbt_database
    ports:
      - "5432:5432"
    networks:
      - my_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  dbt:
    build:
      context: .
      dockerfile: Dockerfile.dbt
    stdin_open: true
    tty: true
    networks:
      - my_network
    volumes:
      - ./my_sample_dbt:/usr/app/my_sample_dbt  # Mount your dbt project               # Mount your dbt profiles (optional, for local profiles)
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  my_network: